import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./theme/ThemeRegistry";

import ClientWrapper from "./ui/utils/ClientWrapper";
import { createTheme } from "@mui/material/styles";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Porcigest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased min-h-screen`}>
        <ThemeRegistry>
          <ClientWrapper>{children}</ClientWrapper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
