import type { Metadata } from "next";
import { Quicksand, Roboto } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./theme/ThemeRegistry";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} antialiased font-semibold min-h-screen flex items-center justify-center`}
      >
        <ThemeRegistry>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
